# See Also: https://gist.github.com/carlwgeorge/c560a532b6929f49d9c0df52f75a68ae
- name: install playbook requirements
  become: true
  package:
    name:
 #     - python3-psutil
      - dconf-cli

- name: install flatpak plugin for gnome-software
  become: true
  package:
    name:
      - gnome-software-plugin-flatpak

- name: Read favorite-apps
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    state: read
  register: dconf_result

- name: Ensure favorite-apps is a list
  set_fact:
    current_list: "{{ dconf_result.value | from_yaml }}"

- name: Remove apps and add Flatpak ones
  set_fact:
    current_list: >-
      {{ ['org.mozilla.firefox.desktop', 'org.mozilla.Thunderbird.desktop'] +
         (current_list | difference(['firefox.desktop', 'org.gnome.Evolution.desktop', 'org.mozilla.firefox.desktop', 'org.mozilla.Thunderbird.desktop'])) }}

- name: Set updated dconf list
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "{{ '[' + (current_list | map('regex_replace', '^(.*)$', \"'\\1'\") | join(', ')) + ']' }}"
    state: present

- name: install extensions
  become: true
  package:
    name:
      - gnome-shell-extension-dashtodock
      - gnome-shell-extension-tiling-assistant
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-appindicator

- name: enable extensions
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['tiling-assistant@leleat-on-github', 'ubuntu-appindicators@ubuntu.com', 'dash-to-dock@micxgx.gmail.com', 'caffeine@patapon.info']"

#   - name: restart gnome-shell
#     ansible.builtin.command: killall -HUP gnome-shell

- name: dash-to-dock move left
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'LEFT'"

- name: dashtodock panel mode
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
    value: true

- name: dashtodock don't autohide
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
    value: true

- name: dashtodock set max-icon-size=32
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size"
    value: 32

- name: dtd shrink theme
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink"
    value: true


- name: don't use custom theme
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/apply-custom-theme"
    value: false

- name: dynamic opactiy
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/customize-alphas"
    value: true

- name: dynamic opacity
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/max-alpha"
    value: 1.0

- name: make app indicators bright
  dconf:
    key: "/org/gnome/shell/extensions/appindicator/icon-brightness"
    value: 1.0
