- name: Get system codename (e.g., bookworm, bullseye, jammy)
  ansible.builtin.command: lsb_release -sc
  register: distro_codename
  changed_when: false

- name: Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: arch_result

# Generally non-free-firmware is enabled by default now
- name: Add contrib repository to sources list
  ansible.builtin.apt_repository:
    repo: "deb https://deb.debian.org/debian/ {{ distro_codename.stdout }} contrib"
    state: present
    filename: contrib
  become: true

- name: Add non-free repository to sources list
  ansible.builtin.apt_repository:
    repo: "deb https://deb.debian.org/debian/ {{ distro_codename.stdout }} non-free"
    state: present
    filename: non-free
  become: true

- name: Add Nvidia container debian repo
  deb822_repository:
    name: nvidia-container-toolkit
    types: deb
    uris: "https://nvidia.github.io/libnvidia-container/stable/deb/{{ arch_result.stdout }}/"
    suites: ["/"]
    components: []
    signed_by: https://nvidia.github.io/libnvidia-container/gpgkey
  become: true

- name: Install Nvidia drivers
  ansible.builtin.apt:
    update_cache: yes
    name:
      - "linux-headers-{{ ansible_kernel }}"
      - firmware-misc-nonfree
      - nvidia-driver
      - nvidia-kernel-dkms
      - nvtop
    state: latest
  become: true

- name: Set Nvidia container toolkit version
  set_fact:
    nvidia_container_toolkit_version: "1.17.8-1"

- name: Install specific Nvidia container toolkit packages
  ansible.builtin.apt:
    name:
      - "nvidia-container-toolkit={{ nvidia_container_toolkit_version }}"
      - "nvidia-container-toolkit-base={{ nvidia_container_toolkit_version }}"
      - "libnvidia-container-tools={{ nvidia_container_toolkit_version }}"
      - "libnvidia-container1={{ nvidia_container_toolkit_version }}"
    state: present
    update_cache: yes
  become: true
