- name: install packages
  become: true
  package:
    name:
      - flatpak
      - podman
      - crun
      - xclip

- name: add flatpak remote
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Install firefox/thunderbird flatpak
  community.general.flatpak:
    name:
      - org.mozilla.firefox
      - org.mozilla.Thunderbird

- name: Ensure firefox-esr is removed
  become: true
  apt:
    name: firefox-esr
    state: absent


- name: Install Additional flatpaks
  community.general.flatpak:
    name:
      - com.logseq.Logseq
      - com.sublimemerge.App
      - net.ankiweb.Anki
      # Communication Platforms
      - org.telegram.desktop
      - com.discordapp.Discord
      - us.zoom.Zoom
      - info.mumble.Mumble
      # Compatibility
      - com.usebottles.bottles
      - io.podman_desktop.PodmanDesktop
      - it.mijorus.gearlever # GTK Manage Appimages
      # Media
      - com.calibre_ebook.calibre
      - com.yacreader.YACReader
      - com.obsproject.Studio
